# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastLm <- function(y, X) {
    .Call('pkgtemplate_fastLm', PACKAGE = 'pkgtemplate', y, X)
}

timesTwo <- function(x) {
    .Call('pkgtemplate_timesTwo', PACKAGE = 'pkgtemplate', x)
}

